name: venv-{{ cookiecutter.project_slug_dashes }}
dependencies:
  - python=3.10
  - numpy

  - jupyter_console
  - black

  # sphinx and dependencies for automatically creating documentation
  - sphinx
  - sphinx_rtd_theme
  - sphinx-autodoc-typehints
  - m2r2
